<?php

namespace AppBundle\Repository;

/**
 * ClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationRepository extends \Doctrine\ORM\EntityRepository
{
}
