<?php

namespace AppBundle\Repository;

/**
 * CompanyCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
