<?php
/**
 * CompanyCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Saswati
 *
 * @category Repository
 */
namespace AppBundle\Repository;

class CompanyCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
