<?php
/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Saswati
 *
 * @category Repository
 */
namespace AppBundle\Repository;

class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
	/**
    * 
    * get customer name and value 
    * It is used to fetch active customer name and value from database on given filters.
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
    public function getCustomerDetail() {
    	$query = $this->createQueryBuilder('c')
                    ->select('c.name')
                    ->addSelect('c.customer as value')
                    ->innerJoin('AppBundle:Status', 's', 'WITH', 'c.status = s.id');
        
        $query->Where('s.name = :name')
                ->setParameter('name', 'ACTIVE');
                             
        return $query->getQuery()->getResult();
    
    }
}
