<?php

namespace AppBundle\Repository;

/**
 * ItemCategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemCategoryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
