<?php

namespace AppBundle\Repository;

/**
 * POItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POItemsRepository extends \Doctrine\ORM\EntityRepository
{
}
