<?php

/**
 * PurchaseOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Saswati
 *
 * @category Repository
 */
namespace AppBundle\Repository;

class PurchaseOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
