<?php

namespace AppBundle\Repository;

/**
 * SubAccountTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubAccountTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
