<?php

namespace AppBundle\Repository;

/**
 * TaxCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
