<?php
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Saswati
 *
 * @category Repository
 */
namespace AppBundle\Repository;

class UserRepository extends \Doctrine\ORM\EntityRepository
{

	/**
    * 
    * check login
    * It is used to check user data in database
    *
    * @param array $data array of coloum name and its values
    * @return array $result containing required data.
    */
    public function loginDetails($value)
    { 
        
        $query = $this->createQueryBuilder('u')
                    ->select('u.id')
                    ->addSelect('u.email as email')]
                    ->leftJoin('AppBundle:Status', 's', 'WITH', 'u.status = s.id')
                    ->Where('u.email = :email')
                    ->setParameter('email',$value['email'])
                    ->andWhere('u.pass = :pass')
                    ->setParameter('pass',$value['password'])
                    ->andWhere('s.name = :status')
                    ->setParameter('status','ACTIVE');
              
        return $query->getQuery()->getResult();
    }
}
