services:
    app.service.default:
        class: AppBundle\Service\DefaultService
        public: true
        arguments: ["@doctrine", "%quickbooks%"]

    app.service.upload:
        class: AppBundle\Service\UploadService
        public: true
        arguments: ["@doctrine", "@app.service.default"]

    app.service.product:
        class: AppBundle\Service\ProductService
        public: true
        arguments: ["@doctrine"]

    app.service.auth:
        class: AppBundle\Service\AuthenticateApiService
        public: true
        arguments: ["%hash_signature_key%"]

    # app.request_listener:
    #     class: AppBundle\EventListener\RequestListener
    #     public: true
    #     arguments: [ "@app.service.auth","@translator" ]
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.request }

    app.service.api_caller:
        class: AppBundle\Service\TestApiService
        public: true

    # app.exception_listener:
    #     class: AppBundle\EventListener\ExceptionListener
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.exception }